version: '2'
services:
  redis:
    image: redis:latest

  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=chat
      - MYSQL_USER=chat
      - MYSQL_PASSWORD=!23qweASD
    ports:
      - 3340:3306
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    links:
      - redis
      - db
    volumes:
      - ./backend:/code
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_HOST=db
      - DATABASE_USERNAME=chat
      - DATABASE_NAME=chat
      - DATABASE_PORT=3306
      - DATABASE_PASSWORD=!23qweASD
      - DATABASE_ENGINE=django.db.backends.mysql

  webfrontend:
     build:
       context: ./webfrontend
     volumes:
       - ./webfrontend:/usr/src/app
     command: npm start
     ports:
       - 80:4200

  mobileapp:
     build:
       context: ./mobileapp
     volumes:
       - ./mobileapp:/usr/src/app
     ports:
       - 8100:8100
